name: Epic Free Games Auto Notifier

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: pip install requests

      - name: 🚀 Run script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python epic

      - name: 🚀 Run script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python steam.py        

      # ✅ Commit & push free.txt if changed
      - name: 📁 Commit & Push free.txt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add free.txt

          # check if there is a change
          git diff --cached --quiet || (
            git commit -m "🔄 Update free games data"
            git push
          )

      - name: 📁 Commit & Push free-steam.txt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add free-steam.txt

          # check if there is a change
          git diff --cached --quiet || (
            git commit -m "🔄 Update free games data"
            git push
          )          
